/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import backend.Projetos;
import backend.Sistema;
import backend.Users;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author marga
 */
public class Projeto extends javax.swing.JFrame {

    private Sistema sistema;
    private Projetos projeto;
    /**
     * Creates new form NovoProjeto
     */
    public Projeto(Sistema sistema, Projetos p) {
        initComponents();
        this.sistema=sistema;
        this.projeto=p;
        getDadosProjeto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeProj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        datai = new com.toedter.calendar.JDateChooser();
        dataf = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto");

        jPanel1.setBackground(new java.awt.Color(1, 75, 84));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText(" Projeto:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 10, 70, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nome do Projeto:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 98, 14);
        jPanel1.add(nomeProj);
        nomeProj.setBounds(20, 60, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Descrição:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 40, 60, 14);

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane1.setViewportView(descricao);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 60, 273, 96);

        jButton1.setBackground(new java.awt.Color(0, 64, 65));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Adicionar Membros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 170, 140, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Data de Início:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 82, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Data de Fim:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 170, 80, 14);

        jButton2.setBackground(new java.awt.Color(0, 64, 65));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Gravar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(500, 300, 70, 23);

        jButton3.setBackground(new java.awt.Color(0, 64, 65));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(405, 300, 90, 23);

        jButton4.setBackground(new java.awt.Color(0, 64, 65));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setText("Lista de Tarefas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(290, 230, 140, 23);

        jButton5.setBackground(new java.awt.Color(0, 64, 65));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setText("Criar Tarefa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(290, 200, 140, 23);
        jPanel1.add(datai);
        datai.setBounds(20, 120, 190, 30);
        jPanel1.add(dataf);
        dataf.setBounds(20, 190, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdicionarMembro adicionar = new AdicionarMembro(sistema, projeto);
        adicionar.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ListaTarefas listat = new ListaTarefas(sistema, projeto);
        listat.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MenuInicial cancela = new MenuInicial(sistema);
        cancela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CriarTarefa criar = new CriarTarefa(sistema, projeto);
        criar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if ((nomeProj.getText().equals("") || (descricao.getText().equals("")) || (getDataInicio().equals(""))) || (getDataFim().equals(""))) {
            javax.swing.JOptionPane.showMessageDialog(this,"É necessário preencher todos os campos!! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            nomeProj.requestFocus();
        } else {
            projeto.setTitulo(nomeProj.getText());
            projeto.setData_inicio(getDataInicio());
            projeto.setData_fim(getDataFim());
            projeto.setDescricao(descricao.getText());
            main.gravou = false;
            sistema.gravaObj(sistema.getDataSave());
            MenuInicial mn = new MenuInicial(sistema);
            mn.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void getDadosProjeto () {
        nomeProj.setText(projeto.getTitulo());
        descricao.setText(projeto.getDescricao());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        if(projeto.getData_inicio() != null && projeto.getData_fim() != null){
            try{
                Date dataIni = formato.parse(projeto.getData_inicio());
                datai.setDate(dataIni);
                Date DataFim = formato.parse(projeto.getData_fim());
                dataf.setDate(DataFim);
            }
            catch(ParseException p){}
        }
    }
    
    private String getDataInicio(){
        try{
        Date dataInicio = datai.getDate();
        DateFormat formato = new SimpleDateFormat (datai.getDateFormatString());        
        String dataI = formato.format(dataInicio);       
        return dataI;
        }catch (NullPointerException n){
            return null;
        }
    }
    
    private String getDataFim(){
        try{
        Date dataFim = dataf.getDate();
        DateFormat formato = new SimpleDateFormat (dataf.getDateFormatString());        
        String dataF = formato.format(dataFim);       
        return dataF;
        }catch (NullPointerException n){
            return null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dataf;
    private com.toedter.calendar.JDateChooser datai;
    private javax.swing.JTextArea descricao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeProj;
    // End of variables declaration//GEN-END:variables
}
