/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import backend.ProjetosList;
import backend.Sistema;
import backend.Users;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author marga
 */
public class Registo extends javax.swing.JFrame {

    private Sistema sistema;
    /**
     * Creates new form Registo
     */
    public Registo(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome_registo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email_registo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pass_registo = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        confpass_registo = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        submeter_registo = new javax.swing.JButton();
        cancelar_registo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        genero = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registo");

        jPanel1.setBackground(new java.awt.Color(0, 75, 84));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Registo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 70, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 40, 14);

        nome_registo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_registoActionPerformed(evt);
            }
        });
        nome_registo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nome_registoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nome_registoKeyTyped(evt);
            }
        });
        jPanel1.add(nome_registo);
        nome_registo.setBounds(20, 60, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 100, 50, 14);

        email_registo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_registoActionPerformed(evt);
            }
        });
        jPanel1.add(email_registo);
        email_registo.setBounds(20, 120, 305, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 160, 70, 14);

        pass_registo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_registoActionPerformed(evt);
            }
        });
        jPanel1.add(pass_registo);
        pass_registo.setBounds(20, 180, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Confirme a password:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 160, 130, 14);

        confpass_registo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confpass_registoActionPerformed(evt);
            }
        });
        jPanel1.add(confpass_registo);
        confpass_registo.setBounds(200, 180, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Género:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(201, 43, 120, 14);

        submeter_registo.setBackground(new java.awt.Color(1, 64, 61));
        submeter_registo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submeter_registo.setForeground(new java.awt.Color(240, 240, 240));
        submeter_registo.setText("Submeter");
        submeter_registo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submeter_registoActionPerformed(evt);
            }
        });
        jPanel1.add(submeter_registo);
        submeter_registo.setBounds(240, 260, 87, 23);

        cancelar_registo.setBackground(new java.awt.Color(1, 64, 61));
        cancelar_registo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelar_registo.setForeground(new java.awt.Color(240, 240, 240));
        cancelar_registo.setText("Cancelar");
        cancelar_registo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_registoActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar_registo);
        cancelar_registo.setBounds(130, 260, 100, 23);

        jLabel7.setBackground(new java.awt.Color(0, 153, 153));
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 180, 330, 120);

        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "Outro" }));
        genero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(genero);
        genero.setBounds(196, 60, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(368, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nome_registoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_registoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_registoActionPerformed

    private void pass_registoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_registoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_registoActionPerformed

    private void nome_registoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_registoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_registoKeyPressed

    private void nome_registoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_registoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_nome_registoKeyTyped

    private void submeter_registoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submeter_registoActionPerformed
        
        if (nome_registo.getText().equals("") || (email_registo.getText().equals("")) || (new String(pass_registo.getPassword()).equals("")) || (new String(confpass_registo.getPassword()).equals(""))){            
            javax.swing.JOptionPane.showMessageDialog(this,"É necessário preencher todos os campos!! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            nome_registo.requestFocus();
        } else if (email_registo.getText().indexOf('@') == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Email inserido inválido \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else if (new String(pass_registo.getPassword()).equals(new String(confpass_registo.getPassword()))){
            Users u = new Users(nome_registo.getText(), email_registo.getText(), new String(pass_registo.getPassword()),((String) genero.getSelectedItem()).trim(), sistema.getUserLogado());
            sistema.getListaUsers().adicionarUsers(u);
            main.gravou = false;
            sistema.gravaObj(sistema.getDataSave());
            Login submeter = new Login(sistema);
            submeter.setVisible(true);
            dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Passwords não correspondem! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_submeter_registoActionPerformed

    private void cancelar_registoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_registoActionPerformed
        // TODO add your handling code here:
        Login cancelar = new Login(sistema);
        cancelar.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelar_registoActionPerformed

    private void email_registoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_registoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_registoActionPerformed

    private void confpass_registoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confpass_registoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confpass_registoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar_registo;
    private javax.swing.JPasswordField confpass_registo;
    private javax.swing.JTextField email_registo;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome_registo;
    private javax.swing.JPasswordField pass_registo;
    private javax.swing.JButton submeter_registo;
    // End of variables declaration//GEN-END:variables
}
